backend:
  name: git-gateway
  branch: main

media_folder: "Asset/uploads"
public_folder: "/Asset/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Meta Description", name: "description", widget: "text" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
